apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-app
  template:
    metadata:
      labels:
        app: basic-app
    spec:
      containers:
      - name: basic-app
        image: basic-app:latest
        ports:
        - containerPort: 3000
